### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by winniewytse** [winniewytse/hcbr#1]
Updated on March 6, 2022
- [x] Merge the `assurance` branch to `main`
- [ ] [Vectorization](https://cran.r-project.org/web/packages/cubature/vignettes/cubature.html)
- [ ] Make the prior plots in the Shiny app conditional
- [x] Rename `r2` to `rsq2`
- [x] Add alpha argument
